import {
  IsNotEmpty,
  IsArray,
  IsString,
  IsOptional,
  IsMongoId,
} from 'class-validator';
import { ObjectId } from 'mongodb';

export class CreateListDto {
  @IsOptional()
  @IsString()
  id?: string; // Optional, generated by the database

  @IsNotEmpty()
  @IsString()
  name: string; // Name of the list

  @IsArray()
  @IsNotEmpty({ each: true }) // Ensure no empty entries in the array
  @IsString({ each: true }) // Ensure each entry is a string
  @IsMongoId({ each: true }) // Validate each entry as a MongoDB ObjectId
  items: string[]; // Array of ObjectId strings

  @IsOptional()
  isList?: boolean = true; // Defaults to true

  @IsOptional()
  createdAt?: Date; // Optional, managed by the database

  @IsOptional()
  updatedAt?: Date; // Optional, managed by the database
}
